import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sav_catalog/foundations/foundations_use_cases.dart';
import 'package:sav_catalog/main.directories.g.dart';
import 'package:sav_catalog/use_cases/sav_button_use_cases.dart';
import 'package:sav_design_system/sav_design_system.dart';
import 'package:widgetbook/widgetbook.dart';

void main() {
  group('catalog structure', () {
    // The navigation tree is generated by build_runner. If a use case is
    // renamed or its annotation dropped, it disappears from the deployed
    // catalog silently — this is what notices.
    test('every expected use case is registered', () {
      final registered = <String, List<String>>{};
      void visit(WidgetbookNode node, String? component) {
        if (node is WidgetbookComponent) {
          registered[node.name] = node.useCases.map((u) => u.name).toList()
            ..sort();
        }
        for (final child in node.children ?? const <WidgetbookNode>[]) {
          visit(child, component);
        }
      }

      for (final node in directories) {
        visit(node, null);
      }

      expect(registered['SavButton'], <String>[
        'All states',
        'In a row',
        'Playground',
        'Specs',
      ]);
      expect(registered['SavColors'], <String>['Palette']);
      expect(registered['SavTypography'], <String>['Type scale']);
      expect(registered['SavSquircle'], <String>['Corner smoothing']);
    });
  });

  group('use cases render', () {
    // The Playground is excluded: it reads `context.knobs`, which only exists
    // inside a running Widgetbook.
    final cases = <String, WidgetBuilder>{
      'button / all states': buildSavButtonMatrix,
      'button / in a row': buildSavButtonRow,
      'button / specs': buildSavButtonSpecs,
      'foundations / palette': buildColorPalette,
      'foundations / type scale': buildTypeScale,
      'foundations / corner smoothing': buildSquircleScale,
    };

    for (final entry in cases.entries) {
      testWidgets(entry.key, (tester) async {
        tester.view.physicalSize = const Size(1400, 2400);
        tester.view.devicePixelRatio = 1;
        addTearDown(tester.view.reset);

        await tester.pumpWidget(
          MaterialApp(
            theme: SavTheme.light(),
            home: Material(child: Builder(builder: entry.value)),
          ),
        );
        await tester.pump();

        expect(tester.takeException(), isNull);
      });
    }
  });
}
